---
os: linux
language: node_js
node_js: 10

dist: trusty

addons:
  chrome: stable
  code_climate:
    repo_token: f15069c85832661086a0f758b25cf410e58ae1f80dbcbc762021dfc71feb8f71

env:
  global:
  - JOBS=1

before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.0
- export PATH=$HOME/.yarn/bin:$PATH
- yarn global add greenkeeper-lockfile@1

install:
- travis_retry yarn install --pure-lockfile

before_script:
- greenkeeper-lockfile-update

script:
- yarn test

after_script:
- greenkeeper-lockfile-upload
- codeclimate-test-reporter < coverage/lcov.info

cache:
  yarn: true
  directories:
  - node_modules

deploy:
  provider: script
  edge: true
  script: ember deploy production --verbose
  on:
    branch: the-future

notifications:
  email: false
  slack: 
    secure: kWuOR9YLV9FRX8wkr/pIvrdLzEcmUG7WYnqkS13T26+o+XyVa3E1ESqmOgCYMU9D0+5jjweRSNRVk7YCKcAwgcMFvwbbMgxVmmPeAOzVant9B1kv8HzdXE7Gd5eipItSxEELYa8ufhVOu5nY/vbCgyr/soPIKbRcDqf3QEXj0a7iWt57bPaRwN/13y1DOy0E1DJuVu4a4oVfsCerVWGYeJafFg7xVVZnvKLS0pqF5zrYuUzvO2hrnGdKz4CvRZym20XDAvhfmG4udcgld2mrxcDF6hJpM3bGDew91/ns+hEyLev44G76Z8XsI/em9d0FQfe27zdzIfaTOWUKY72fbgrJX+YU+HjS5MHRzgZE79nS8b+91VM1EazGPeHsy93ihdXoqkQ0vHHZgxzpjbTBXmLUgRCk3Vb5tc5wspEWTjOi2X7UAUQG3n9iiy7vMfu+/4HUgG8kL97MjmZaNSYTcfv0UDvU8nssRyD/rqMD/Vy6ZXhU/O0Hn47A6a2sgcXXw4neJwwDAC4hKBY89WeCYU6YQU+CnKuc7kHcDmjHBvbV+gXRBQitC5ew3ZZhloDBJYkD52MMOrsgxj+gt6JypKXdX0kXNnXt2HfsbazX/EJMSEL4XMLsmDWzhociFBTLz7QhdznBUg7p6X5kwyM1L0FihTsc+s3Bag/h/CNk5Ag=
